apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: logserver
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: logserver
    app.kubernetes.io/part-of: trillian
  name: logserver
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: logserver
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: logserver
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian/logserver@sha256:0b5e13af959065fdd20957ec88b4003322034b4aa05e505c4fe8cfbb20d58f81
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 6379
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
