apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: database
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: database
    app.kubernetes.io/part-of: trillian
  name: database
spec:
  ports:
  - name: http-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  - name: "6379"
    port: 6379
    targetPort: 6379
  selector:
    app: go-app
    app.kubernetes.io/instance: database
status:
  loadBalancer: {}
