apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: netcat
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian/netcat@sha256:8b85f242f4e33076867c47bb780d30623e7024b26d1ed313d6e08b52cf4a4ece
        name: my-go
        resources: {}
status: {}
