apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netcat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netcat
    app.kubernetes.io/part-of: trillian
  name: netcatpnqj
spec:
  path: /
  port:
    targetPort: 6379
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: netcat
    weight: null
status: {}
