apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: redis
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: redis
    app.kubernetes.io/part-of: trillian
  name: redis
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: redis
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: redis
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian/redis@sha256:c12a4a1dc85ce25d660e9efc921050889b838ce458137a0d5a84052d29486468
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 6379
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
