apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: logsigner
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian/logsigner@sha256:b958322b5e3017c4fe62d260fbd85f7ebe319f334a0074fc7d9424fea69e2e76
        name: my-go
        resources: {}
status: {}
