apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: redis
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian/redis@sha256:df72f395f2aba1d2b84bcdbe55f0a855b31475e090d02da7d5026168d4dcd837
        name: my-go
        resources: {}
status: {}
