apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: redis
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian/redis@sha256:8c12d98f96ed3daa3ea7ce03d52e8b6748c4b7ab20eee98c1d1ad031d14af00e
        name: my-go
        resources: {}
status: {}
