apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: redis
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian/redis@sha256:988711be1dc9649dc831c7b4866058660475b8f94b4209662dbe7c587c05e7ac
        name: my-go
        resources: {}
status: {}
