apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: logsigner
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: logsigner
    app.kubernetes.io/part-of: trillian
  name: logsigner
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: logsigner
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: logsigner
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian/logsigner@sha256:b958322b5e3017c4fe62d260fbd85f7ebe319f334a0074fc7d9424fea69e2e76
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 6379
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
