apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: logserver
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian/logserver@sha256:cf7e4bc39809a6a6793c29021781271f9baaa0ceb82b41e5eb5a3a66572b4e2a
        name: my-go
        resources: {}
status: {}
