apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: netcat
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: netcat
    app.kubernetes.io/part-of: trillian
  name: netcat
spec:
  replicas: 0
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: netcat
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: netcat
    spec:
      containers:
      - image: quay.io/redhat-user-workloads/rhtas-tenant/trillian/netcat@sha256:1b3f860a2616eb2b3faa3b7f762dab245002443146ad2559ab983849483f8c39
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        - containerPort: 6379
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
